### ISSUE TITLE
documentation explains the need of 2 stripe accounts, but does not explain why. Why can't we use a single stripe account?

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#24]
documentation explains the se of 2 stripe accounts, but does not explain why. Why can't we use a single stripe account?

**Comment by huntario** [comment]
Hunter, with BigCommerce here again.

The app is designed this way so that different merchants, each with their own Stripe accounts, can connect to the app developer’s single Stripe account. Through the installation process the merchant grants permission to the app developer’s Stripe account to take certain actions on the merchant’s Stripe account, for example process subscription charges. 

This statement from the accompanying article sums it up “When the app initiates subscription charges, it will use the merchant's dedicated public key with the app's dedicated secret key.  - https://developer.bigcommerce.com/api-docs/partner/subscription-solutions/foundation-guide#configure-stripe  This allows for the granting and revoking of permissions in an automated and secure way rather than manually sharing Stripe API keys. 

Stripe uses the term account somewhat loosely, and really it’s like a sub-account (same email address, dashboard, etc.). For situations where the merchant and app developer are the same entity, I would recommend creating the additional (sub)accounts. 

I hope that helps clarify this situation. I’ll pass this feedback along to our team so that they can review and potentially find ways to clarify this in the article.
